### ISSUE TITLE
Getting this error as I try to predict or train.

### ISSUE THREAD

**Issue by Aakanksha-Rana** [neuronets/zoo#22]
python version: Python 3.7.4
singularity: 2.6.1-dist
also got same error when I used docker (Docker version 20.10.8)
  
Predict
```
(base) aakanksha@aakanksha-Alienware-Aurora-R8:~/zoo$ nobrainer-zoo predict -m neuronets/brainy/0.1.0 /home/aakanksha/T1.mgz /home/aakanksha
Traceback (most recent call last):
  File "/home/aakanksha/.local/bin/nobrainer-zoo", line 11, in <module>
    load_entry_point('nobrainer-zoo', 'console_scripts', 'nobrainer-zoo')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/aakanksha/zoo/nobrainerzoo/cli.py", line 66
    **_option_kwds,
                  ^
SyntaxError: invalid syntax
```

Train: 
```
aakanksha@aakanksha-Alienware-Aurora-R8:~/zoo$ nobrainer-zoo train -m neuronets/brainy
Traceback (most recent call last):
  File "/home/aakanksha/.local/bin/nobrainer-zoo", line 11, in <module>
    load_entry_point('nobrainer-zoo', 'console_scripts', 'nobrainer-zoo')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/aakanksha/zoo/nobrainerzoo/cli.py", line 66
    **_option_kwds,
                  ^
SyntaxError: invalid syntax
```

**Comment by djarecka** [comment]
where do you run it? what is the python version?

**Comment by Aakanksha-Rana** [comment]
I ran it on my local machine. sorry forgot to add some details before, adding it now :)

**Comment by Hoda1394** [comment]
I tried the zoo in a Conda environment with Python 3.7.4 and the latest version of Click (8.0.3) and do not get this error. Can you try it on another operating system?

**Comment by djarecka** [comment]
I also can't repeat, so @Aakanksha-Rana if you still have it we should set a time  to see it

**Comment by Aakanksha-Rana** [comment]
So this looks like version problem. With python 3.7 and Singularity 3.8.5 the errors dont appear. Thankyou @Hoda1394 @djarecka  ^^
