### ISSUE TITLE
Unable to follow instructions on repository home page

### ISSUE THREAD

**Issue by neurolabusc** [neuronets/zoo#42]
1. The [project web page](https://github.com/neuronets/nobrainer-zoo) has a broken link:

```
List of models which will be added in near future can be find [here](https://github.com/Hoda1394/zoo/blob/add/inference_scripts/models_to_add.md).
```

2. Assuming the [link was supposed to point to this page that was last updated two years ago](https://github.com/neuronets/nobrainer-zoo/blob/c6230e99ccea6ec5a09d6ca899a99e71147e6a2b/models_to_add.md) it would be nice to have an update to the models to be added to the `zoo in near future`. It seems some listed have been added (e.g. `DDIG/SynthStrip/1.0.0`) but most have not. 

3. I would suggest that the instructions on the home page are tested with the current release. The instructions suggest that the the software would create `a cache folder in your home directory (~/.nobrainer)` however this failed.

```
$ conda create -n nobrainer-zoo python=3
$ conda activate nobrainer-zoo
$ pip install nobrainer-zoo
$ pip install https://github.com/neuronets/nobrainer-zoo/archive/refs/heads/main.zip

$ nobrainer-zoo init
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/nobrainer-zoo", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
```

4. Therefore, to get the install to succeed I needed to manually generate the folder (`mkdir ~/.nobrainer`) 

5. At the stage, on my M2 Pro MacBook things appeared installed, and I could list the models. However, running the first model suggested in the home page failed.

```
nobrainer-zoo predict -m neuronets/brainy/0.1.0 ./FastSurfer/t1_crop.nii.gz ./test.nii
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/nobrainer-zoo", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nobrainerzoo/cli.py", line 299, in predict
    image = _container_check(
            ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nobrainerzoo/cli.py", line 1037, in _container_check
    raise Exception(f"{container_type} is not installed.")
Exception: singularity is not installed.
```

**Comment by hvgazula** [comment]
Hi Chris (@neurolabusc), M* processors cannot run singularity directly unless you are running on a VM. Please use a Linux environment for the time being. I will keep addressing the other points over the next few days.

**Comment by neurolabusc** [comment]
OK, given the prevalence of this architecture in our domain, you might want to add a quick check of the architecture when your script starts, and provide the user with an interpretable message.
